apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-04
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-04
  strategy: {}
  template:
    metadata:
      labels:
        app: mongo-04
    spec:
      containers:
      - image: mongo:5.0.21
        name: mongo
        args: ["--dbpath","/data/db", "--config", "/mnt/mongod.conf"]
#        args: ["--dbpath","/data/db"]
        volumeMounts:
        - mountPath: /mnt/mongod.conf
          name: vmongod-01-conf
          subPath: mongod.conf
        resources:
          limits:
            cpu: "0.01"
          requests:
            cpu: "0.01"
      volumes:
      - name: vmongod-01-conf
        configMap:
          name: mongod-01-conf
          items:
          - key: key1
            path: mongod.conf
